### ISSUE TITLE
Control which kubernetes nodes chaincode runs on

### ISSUE THREAD

**Issue by jt-nti** [hyperledger-labs/fabric-builder-k8s#228]
It may be desirable to control which kubernetes nodes chaincode runs on. For example, to use a pool of nodes specifically for running chaincode on, or to run the chaincode on the same node as the peer.

Covering all possible use cases is outside the scope of the k8s builder and should be handled with a Dynamic Admission Control using a Mutating Webhook. For example, it looks like the [namespace-node-affinity](https://github.com/idgenchev/namespace-node-affinity) webhook could be used to assign node affinity and tolerations to all pods in the `FABRIC_K8S_BUILDER_NAMESPACE` namespace.

Developing and deploying a webhook is not trivial though, so optionally adding basic affinity and toleration to chaincode pods may be useful for simple deployments. For example,

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      – matchExpressions:
        – key: hlf-node-role/chaincode
          operator: Exists
tolerations:
- key: "hlf-node-role/chaincode"
  operator: "Exists"
  effect: "NoSchedule"
```

Chaincode nodes would then need a corresponding taint. For example,

```shell
kubectl taint nodes node1 hlf-node-role/chaincode:NoSchedule
```

**Comment by davidfdr** [comment]
Very nice upgrade!

**Comment by labibfarag** [comment]
Also we have to consider that NOT all CC run on the same nodes , we need a separation
in our requirements each orgs has a set of nodes ,
so the
chaincodes for Org1 run on nodes managed by Org1 ex: node1,
chaincodes for Org2 run on nodes managed by Org2 ex: node2,

**Comment by jt-nti** [comment]
I think adding a new `FABRIC_K8S_BUILDER_NODE_ROLE` configuration option should work.

For example, in the simple case with the node role set to "chaincode" the following affinity and toleration would be added:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "fabric-builder-k8s-role"
          operator: In
          values:
          - "chaincode"
tolerations:
- key: "fabric-builder-k8s-role"
  operator: "Equal"
  value: "chaincode"
  effect: "NoSchedule"
```

Nodes with the matching label and taint should then be dedicated to running chaincode. For example:

```shell
kubectl label nodes node1 fabric-builder-k8s-role=chaincode
kubectl taint nodes node1 fabric-builder-k8s-role=chaincode:NoSchedule
```

To handle the case where you want different nodes running different chaincode, different node roles could be configured. For example, "org1cc", "org2cc", etc.

Does that sound ok?
