### ISSUE TITLE
Sample docker images should include a name/path prefix

### ISSUE THREAD

**Issue by jkneubuh** [hyperledger-labs/fabric-builder-k8s#61]
The .github/workflows for building, preparing, and publishing chaincode images and packages are awesome.  Awesome.  💯 ❤️ 

The images created by the build could use a little bit of context.  For instance, the `contract-java` and `contract-node` images are being published to the container registry as: 

- ghcr.io/hyperledger-labs/contract-java@sha256:.... 
- ghcr.io/hyperledger-labs/contract-node@sha256:... 

I don't think that is correct.  The image output paths should include the application/repo/folder/etc. context in the URLs. 

I was able to change the path for the published images by passing the full path, e.g.: 
```
jobs:
  docker_build:
    name: Docker build
    uses: ./.github/workflows/docker-build.yaml
    with:
      imagename: full-stack-asset-transfer-guide/contracts/asset-tx-typescript
      path: contracts/asset-tx-typescript
      chaincode: true
```

With this update, publish steps upload the image correctly as ghcr.io/hyperledgendary/full-stack-asset-transfer-guide/contracts/asset-tx-typescript@sha256:....    This is good. 

But when passing the full path in for the `imagename` attribute to the package-k8s-chaincode-action, the ${imagename}.tgz package output can not be found, as (I think) it's being generated up at the root folder in the hierarchy.  Or the first path element is not available, or ... something.   I think where this starts to go off the rails is where docker-build.yaml is passing ${{inputs.imagename}} in for `chaincode-label` to the package action.
